name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PVS-Studio
      run: |
        wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt | sudo apt-key add -
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.pvs-studio.com/etc/viva64.list
        sudo apt update -qq
        sudo apt install -qq -y pvs-studio

    - name: Configure PVS-Studio
      run: pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

    - name: Setup python3
      run: sudo apt-get install -qq -y python3 python3-pip

    - name: Setup ninja-build
      run: sudo apt-get install -qq -y ninja-build

    - name: Setup meson
      run: python3 -m pip install meson

    - name: Setup glib-2.0
      run: sudo apt-get install -qq -y libglib2.0-dev

    - name: Setup clang-format-15
      run: sudo apt-get install -qq -y clang-format-15

    - name: Setup clang-tidy-15
      run: sudo apt-get install -qq -y clang-tidy-15

    - name: Lint clang-format
      run: scripts/lint-clang-format.sh

    - name: Lint clang-tidy
      run: scripts/lint-clang-tidy.sh

    - name: Lint PVS-Studio
      run: scripts/lint-pvs-studio.sh
