name: PVS-Studio

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  analyze:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup PVS-Studio
        env:
          PVS_STUDIO_VERSION: 7.34.87460.207
        run: |
          wget "https://files.pvs-studio.com/pvs-studio-$PVS_STUDIO_VERSION-amd64.deb"
          sudo dpkg -i "pvs-studio-$PVS_STUDIO_VERSION-amd64.deb"
          sudo apt-get install -f

      - name: Configure PVS-Studio
        run: pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

      - name: Setup clang++
        run: sudo apt-get install -qq -y clang

      - name: Setup python3
        run: sudo apt-get install -qq -y python3 python3-pip

      - name: Setup ninja-build
        run: sudo apt-get install -qq -y ninja-build

      - name: Setup meson
        run: python3 -m pip install meson

      - name: Setup glib-2.0
        run: sudo apt-get install -qq -y libglib2.0-dev

      - name: Build
        run: |
          meson setup builddir
          meson compile -C builddir

      - name: Analyze
        run: pvs-studio-analyzer analyze -f builddir/compile_commands.json -j

      - name: Convert report
        run: plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: Publish report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
